<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta name="language" content="ro" />
	<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
	<title>EvidPac - Account</title>
	<link href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="http://yui.yahooapis.com/2.7.0/build/base/base-min.css" media="screen" rel="stylesheet" type="text/css" />
	<!--[if lte IE 9]><script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
	<div id="container" class="container">
		<div id="header" class="span-24 last">
			<h1 id="evidpac"><a href="/">EvidPac</a></h1>
			<p>Aplicatie pentru evidenta pacientilor din psihiatrie</p>
                        <h3>Account User</h3>
		</div>
		<div id="meniu" class="span-24 last"><?=$meniu?></div>
		<div id="content" class="span-24 last"><?=$content?></div>
		<div id="footer" class="span-24 last">
			Proiect realizat de Mihaela Brahariu (Birladeanu)<br/>PHP version: <?=phpversion()?>
		</div>
	</div>
</body>
</html>